### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by sheepzh** [outofambit/outofambit#1]
Hello, I like to write poems, too, but in Chinense. 

Could you allow me to translate some poems written by you in *poems for chelsea manning* into Chinese,  I like them. 

And I wanna post the translated in my personal wechat account.

**Comment by outofambit** [comment]
hi @sheepzh! that's so sweet of you 🥺 i'd be honored if you would translate them. would you credit me as original author when you post them in your wechat?

if you share your translations back with me i could include them on my website too (and credit you). that would be neat! 😃 

out of curiosity, which poems did you want to translate?

if you email me at `coding@outofambit.com`, we can keep chatting on email about this too 💜
